import { MajorArcanaCard, toCardId } from './tarot-card';

type MajorArcanaEntry = [
  name: string,
  astrology: string,
  keywords: string[],
  upright: string,
  reversed: string,
];

/** Ordered by card number (Rider-Waite: Strength is 8, Justice is 11); astrology follows the Golden Dawn. */
const ENTRIES: readonly MajorArcanaEntry[] = [
  [
    'The Fool',
    'Air',
    ['beginnings', 'spontaneity', 'leap of faith'],
    'A fresh start taken with open hands and little baggage.',
    'Recklessness, or a leap postponed out of fear.',
  ],
  [
    'The Magician',
    'Mercury',
    ['will', 'skill', 'manifestation'],
    'Every tool you need is already on the table.',
    'Scattered talent, or intent used to manipulate.',
  ],
  [
    'The High Priestess',
    'Moon',
    ['intuition', 'mystery', 'inner knowing'],
    'The answer is quiet and already inside you.',
    'Ignoring your intuition, or secrets kept too long.',
  ],
  [
    'The Empress',
    'Venus',
    ['abundance', 'nurture', 'creativity'],
    'Growth that comes from care, comfort and creation.',
    'Smothering, or creative energy left untended.',
  ],
  [
    'The Emperor',
    'Aries',
    ['structure', 'authority', 'stability'],
    'Order, boundaries and a steady hand at the helm.',
    'Rigidity, or control that has turned into domination.',
  ],
  [
    'The Hierophant',
    'Taurus',
    ['tradition', 'guidance', 'belonging'],
    'Wisdom passed down through teachers and shared rituals.',
    'Questioning the rules and finding your own path.',
  ],
  [
    'The Lovers',
    'Gemini',
    ['union', 'choice', 'alignment'],
    'A meaningful bond, or a choice that reflects your values.',
    'Disharmony, or a decision made against yourself.',
  ],
  [
    'The Chariot',
    'Cancer',
    ['drive', 'willpower', 'victory'],
    'Momentum earned by holding opposing forces together.',
    'Lost direction, or forcing progress that will not come.',
  ],
  [
    'Strength',
    'Leo',
    ['courage', 'patience', 'compassion'],
    'Quiet courage that tames rather than conquers.',
    'Self-doubt, or strength turned into harshness.',
  ],
  [
    'The Hermit',
    'Virgo',
    ['solitude', 'reflection', 'inner guidance'],
    'Stepping back to find the light you already carry.',
    'Isolation that has stopped being useful.',
  ],
  [
    'Wheel of Fortune',
    'Jupiter',
    ['cycles', 'change', 'fate'],
    'The wheel turns; a new chapter is starting.',
    'Resisting change, or a run of bad luck.',
  ],
  [
    'Justice',
    'Libra',
    ['fairness', 'truth', 'cause and effect'],
    'Clear eyes, honest scales and consequences that fit.',
    'Unfairness, or avoiding accountability.',
  ],
  [
    'The Hanged Man',
    'Water',
    ['surrender', 'new perspective', 'pause'],
    'Letting go and seeing the situation upside down.',
    'Stalling, or a sacrifice that leads nowhere.',
  ],
  [
    'Death',
    'Scorpio',
    ['endings', 'transformation', 'release'],
    'An ending that clears space for something new.',
    'Clinging to what is already over.',
  ],
  [
    'Temperance',
    'Sagittarius',
    ['balance', 'moderation', 'patience'],
    'Blending opposites slowly into something whole.',
    'Excess, or impatience upsetting the balance.',
  ],
  [
    'The Devil',
    'Capricorn',
    ['attachment', 'temptation', 'shadow'],
    'Chains that are looser than they look.',
    'Breaking free from a habit or a hold.',
  ],
  [
    'The Tower',
    'Mars',
    ['upheaval', 'revelation', 'sudden change'],
    'A sudden shake-up that exposes what was unstable.',
    'Avoiding a necessary collapse, or rebuilding after one.',
  ],
  [
    'The Star',
    'Aquarius',
    ['hope', 'renewal', 'inspiration'],
    'Calm hope and healing after the storm.',
    'Discouragement, or faith that needs rekindling.',
  ],
  [
    'The Moon',
    'Pisces',
    ['illusion', 'dreams', 'the unknown'],
    'Uncertain paths lit by intuition rather than facts.',
    'Confusion lifting, or fears seen for what they are.',
  ],
  [
    'The Sun',
    'Sun',
    ['joy', 'success', 'vitality'],
    'Warmth, clarity and well-earned joy.',
    'Joy clouded over, or optimism taken too far.',
  ],
  [
    'Judgement',
    'Fire',
    ['awakening', 'reckoning', 'calling'],
    'A wake-up call and a chance to rise renewed.',
    'Harsh self-judgement, or ignoring the call.',
  ],
  [
    'The World',
    'Saturn',
    ['completion', 'integration', 'wholeness'],
    'A cycle completed and a sense of arrival.',
    'Loose ends, or a finish line that keeps moving.',
  ],
];

export const MAJOR_ARCANA: readonly MajorArcanaCard[] = ENTRIES.map(
  ([name, astrology, keywords, upright, reversed], number) => ({
    id: toCardId(name),
    name,
    number,
    arcana: 'major',
    astrology,
    keywords,
    upright,
    reversed,
  }),
);
